name: fusil.yml
on:
  pull_request:

jobs:
  fuzz:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.14t

    steps:
      - name: Install pyenv
        run: |
          git clone --single-branch --depth=1 --no-tags \
          https://github.com/pyenv/pyenv.git "./.pyenv"
          export PYENV_ROOT="./.pyenv"
          export PYENV_BIN="$PYENV_ROOT/bin"
          export PYENV_SHIMS="$PYENV_ROOT/shims"
          export PYENV_CACHE="$PYENV_ROOT/cache"
          mkdir "$PYENV_CACHE"
          alias pyenv='./.pyenv/bin/pyenv'
      - name: build python with sanitizers
        run: |
          export CONFIGURE_OPTS="--disable-gil --with-pydebug --with-address-sanitizer --without-pymalloc --without-system-libmpdec --config-cache" 
          pyenv install --verbose --keep ${{ matrix.python-version }}
          pyenv global ${{ matrix.python-version }}
          export CUSTOM_PYTHON="$(pyenv which python)"
      - uses: actions/checkout@v4
      - name: install dependencies
        run: |
          pip install python-ptrace git+https://github.com/devdanzin/fusil.git ".[dev]"
      - name: prepare runs directory
        run: |
          mkdir -p -m 777 ./fusil/runs
      - name: run fusil
        run: |
          export ASAN_OPTIONS=detect_leaks=0
          export PYTHON_GIL=0
          fusil-python-threaded \
            --python="$CUSTOM_PYTHON" \
            --force-unsafe \
            -v \
            --success=200 \
            --fast \
            --test-private \
            --packages=cereggii \
            --no-async \
            --no-numpy \
            --no-tstrings
